# This is a basic workflow to help you get started with actions

name: Python script

# Controls when triggers the workflow will run
on:
  
   #allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contain a sigle job called "build"
  build:
    #

    # Steps represents a sequence of tasks that will be executed as part of the job
    step:
      # checks-out your repositories under $GITHUB_WORKSPCE, so your job can access it
      - uses: actions/checkout@v3

      # runs a single command using the runners shell
      - name: Run a Python Script
        run: python .github/workflows/example.py
    
